language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ronsonw/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ronsonw/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: 'us-west-2'
    app: 'docker-react'
    env: 'DockerReact-env'
    bucket_name: 'arn:aws:s3:::elasticbeanstalk-us-west-2-850652371396'
    bucket_path: 'docker-react'
    # deploy when the code is push to master
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
